CREATE TABLE courses
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    archived             BOOLEAN,
    name                 VARCHAR(255),
    institution          VARCHAR(255),
    location             VARCHAR(255),
    province_id          BIGINT,
    level                VARCHAR(255),
    courseType           VARCHAR(255),
    housekeepingRelated  BOOLEAN,
    timeOccupation       VARCHAR(255),
    region               VARCHAR(255),
    collaboration        BOOLEAN,
    responsibleTaskForce VARCHAR(255),
    professor            VARCHAR(255),
    contact              VARCHAR(255),
    web                  VARCHAR(255),
    explanation          VARCHAR(255),
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE provinces
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_provinces PRIMARY KEY (id)
);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_PROVINCE FOREIGN KEY (province_id) REFERENCES rijksoverheid.provinces (id);