
CREATE TABLE courses
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    archived               BOOLEAN NOT NULL,
    name                   VARCHAR(255),
    institution            VARCHAR(255) NOT NULL,
    location               VARCHAR(255) NOT NULL,
    province_id            BIGINT NOT NULL,
    level                  VARCHAR(255),
    course_type            VARCHAR(255),
    housekeeping_related   BOOLEAN NOT NULL,
    time_occupation        VARCHAR(255),
    region                 VARCHAR(255),
    collaboration          BOOLEAN,
    responsible_task_force VARCHAR(255),
    professor              VARCHAR(255),
    contact                VARCHAR(255),
    web                    VARCHAR(255),
    explanation            VARCHAR(255),
    CONSTRAINT pk_courses  PRIMARY KEY (id)
);

CREATE TABLE provinces
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_provinces PRIMARY KEY (id)
);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_PROVINCE FOREIGN KEY (province_id) REFERENCES provinces (id);

CREATE TABLE users (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username varchar(255) PRIMARY KEY NOT NULL,
    password varchar(255) NOT NULL,
    authority_string varchar(255)
);
