server.port=8081
server.servlet.context-path=/rijksoverheid/api

spring.datasource.url=jdbc:postgresql://db:5435/rijksoverheid
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.open-in-view=false

spring.flyway.schemas=rijksoverheid
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

springdoc.show-login-endpoint=true
springdoc.swagger-ui.path=/swagger-ui.html
