server.port=8081
server.servlet.context-path=/rijksoverheid/api

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres


spring.jpa.open-in-view=false
#management.health.ldap.enabled=false

spring.flyway.schemas=rijksoverheid
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

springdoc.show-login-endpoint=true
springdoc.swagger-ui.path=/swagger-ui.html

jwt.secret=onwijsgeheimpje
#spring.flyway.locations='D:/Users/roben/Documents/Computing Science PM/Software Engineering/Rijksoverheid/backend/src/main/resources/db/migration
