name: Build Backend
on:
  pull_request:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.10.1
#        with:
#          access_token: ${{ github.token }}

      - name: "checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: "setup java"
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: "add executable permission to gradlew script"
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: "build backend"
        run: ./gradlew :bootJar
        working-directory: ./backend
